version: '3.8'

services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voyage-project-cda
      MYSQL_USER: admin
      MYSQL_PASSWORD: password